CREATE TABLE Venue(
	Id INT IDENTITY(1,1) PRIMARY KEY, 
	VenueName VARCHAR (250) NOT NULL,
	Location VARCHAR (250) NOT NULL,
	Capacity INT,
	ImageURL VARCHAR (250) NOT NULL
);

CREATE TABLE Event(
	Id INT IDENTITY(1,1) PRIMARY KEY, 
	VenueId INT NOT NULL,
	EventName VARCHAR (250) NOT NULL,
	EventDate DATE NOT NULL,
	Description VARCHAR (250) NOT NULL,
	CONSTRAINT FK_Event_Venue FOREIGN KEY (VenueId) REFERENCES Venue(Id), 
);

CREATE TABLE Booking(
	Id INT IDENTITY(1,1) PRIMARY KEY, 
	VenueId INT NOT NULL, 
	EventId INT NOT NULL, 
	BookingDate DATE NOT NULL,
	CONSTRAINT FK_Booking_Venue FOREIGN KEY (VenueId) REFERENCES Venue(Id), 
	CONSTRAINT FK_Booking_Event FOREIGN KEY (EventId) REFERENCES Event(Id) 
);